//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int ansno { get; set; }
        public Nullable<int> qno { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> sno { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
