//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResond
    {
        public int userId { get; set; }
        public Nullable<int> sum { get; set; }
        public Nullable<int> qno { get; set; }
        public Nullable<int> response { get; set; }
    }
}
